name: Daily Wastage Report to Dropbox

on:
  schedule:
    - cron: '0 6 * * *'  # every day at 06:00 UTC
  workflow_dispatch:     # allows manual trigger

jobs:
  run-daily-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run daily-report.js
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: node scripts/daily-report.js
