name: Daily Wastage Report

on:
  schedule:
    - cron: '0 6 * * *'  # Run at 6 AM UTC
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm ci
        echo "Checking scripts directory:"
        ls -la scripts/
        echo "Verifying daily-reports.cjs exists:"
        test -f scripts/daily-reports.cjs || exit 1

    - name: Remove old script if it exists
      run: |
        rm -f scripts/email-report.js || true
        echo "Remaining scripts:"
        ls -la scripts/

    - name: Generate report
      env:
        APP_URL: ${{ secrets.APP_URL }}
        EXPORT_TOKEN: ${{ secrets.EXPORT_TOKEN }}
      run: |
        echo "Running daily reports script..."
        if [ ! -f "scripts/daily-reports.cjs" ]; then
          echo "Error: daily-reports.cjs not found!"
          ls -la scripts/
          exit 1
        fi
        node scripts/daily-reports.cjs > report.txt
        echo "Report generated. Content:"
        cat report.txt

    - name: Create Issue with Report
      if: success()
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const reportContent = fs.readFileSync('report.txt', 'utf8');
          const today = new Date().toISOString().split('T')[0];
          
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Daily Wastage Report - ${today}`,
            body: '```\n' + reportContent + '\n```',
            labels: ['report', 'automated']
          });
