name: Daily Wastage Report to Dropbox

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-daily-report:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Increased timeout

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Wait for Railway application
      run: |
        URL="${APP_URL:-https://wastagetracker-production.up.railway.app}"
        echo "Waiting for application to be available at: $URL"
        MAX_ATTEMPTS=10
        ATTEMPT=1
        SUCCESS=false

        while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
          echo "Attempt $ATTEMPT/$MAX_ATTEMPTS..."
          
          RESPONSE=$(curl -s -w "\n%{http_code}" "$URL")
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo "Response code: $HTTP_CODE"
          echo "Response body: $BODY"
          
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Application is responding successfully"
            SUCCESS=true
            break
          fi
          
          echo "⚠️ Application returned HTTP $HTTP_CODE"
          if [ $ATTEMPT -lt $MAX_ATTEMPTS ]; then
            SLEEP_TIME=30
            echo "Waiting $SLEEP_TIME seconds before next attempt..."
            sleep $SLEEP_TIME
          fi
          
          ATTEMPT=$((ATTEMPT + 1))
        done

        if [ "$SUCCESS" != "true" ]; then
          echo "❌ Application failed to respond after $MAX_ATTEMPTS attempts"
          echo "Last response code: $HTTP_CODE"
          echo "Last response body: $BODY"
          echo "Please check Railway deployment status"
          exit 1
        fi
      env:
        APP_URL: ${{ secrets.APP_URL }}

    - name: Run daily-reports.cjs with retries
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        APP_URL: ${{ secrets.APP_URL }}
        NODE_DEBUG: http,https
      run: |
        MAX_ATTEMPTS=5
        ATTEMPT=1
        SUCCESS=false

        while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
          echo "Attempt $ATTEMPT/$MAX_ATTEMPTS to run daily report..."
          
          if node scripts/daily-reports.cjs; then
            echo "✅ Report generated successfully"
            SUCCESS=true
            break
          fi
          
          if [ $ATTEMPT -lt $MAX_ATTEMPTS ]; then
            SLEEP_TIME=60
            echo "⚠️ Attempt failed, waiting $SLEEP_TIME seconds before retry..."
            sleep $SLEEP_TIME
          fi
          
          ATTEMPT=$((ATTEMPT + 1))
        done

        if [ "$SUCCESS" != "true" ]; then
          echo "❌ All attempts failed"
          exit 1
        fi
