name: Daily Wastage Report to Dropbox

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-daily-report:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Set a timeout to avoid hanging

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Check application health
      env:
        APP_URL: ${{ secrets.APP_URL }}
      run: |
        # Use APP_URL from secrets or default to production URL
        URL="${APP_URL:-https://wastagetracker-production.up.railway.app}"
        echo "Checking application health at: $URL"
        for i in {1..5}; do
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
          if [ $HTTP_CODE -eq 200 ]; then
            echo "✅ Application is healthy (HTTP $HTTP_CODE)"
            break
          fi
          echo "⚠️ Attempt $i: Application returned HTTP $HTTP_CODE"
          if [ $i -lt 5 ]; then
            echo "Waiting 30 seconds before retry..."
            sleep 30
          else
            echo "❌ Application health check failed after 5 attempts"
            exit 1
          fi
        done

    - name: Run daily-reports.cjs
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        APP_URL: ${{ secrets.APP_URL }}
        NODE_DEBUG: http,https  # Enable HTTP debugging
      run: |
        # First try without debug
        if node scripts/daily-reports.cjs; then
          echo "✅ Report generated successfully"
          exit 0
        fi
        
        echo "⚠️ First attempt failed, retrying with debug..."
        # If failed, retry with debug logging
        node scripts/daily-reports.cjs
