name: Daily Wastage Report

on:
  schedule:
    - cron: '0 6 * * *'  # Run at 6 AM UTC
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm ci
        npm install nodemailer dayjs node-fetch
        echo "Checking scripts directory:"
        ls -la scripts/
        echo "Verifying daily-reports.cjs exists:"
        test -f scripts/daily-reports.cjs || exit 1

    - name: Send email report
      env:
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        REPORT_EMAIL: 'thecastle.orders@gmail.com'
        APP_URL: ${{ secrets.APP_URL }}
        EXPORT_TOKEN: ${{ secrets.EXPORT_TOKEN }}
      run: |
        echo "Running daily report script..."
        node scripts/daily-reports.cjs
