name: Monthly Wastage Report

on:
  schedule:
    - cron: '0 6 1 * *'  # Run at 6 AM UTC on the first day of each month
  workflow_dispatch:
    inputs:
      report_date:
        description: 'Report date (YYYY-MM-DD format). Leave empty for last month.'
        required: false
        type: string

jobs:
  send-report:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm ci
        npm install nodemailer dayjs node-fetch
        echo "Checking scripts directory:"
        ls -la scripts/
        echo "Verifying monthly-report.js exists:"
        test -f scripts/monthly-report.js || exit 1

    - name: Send email report
      env:
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        REPORT_EMAIL: 'thecastle.orders@gmail.com'
        APP_URL: ${{ secrets.APP_URL }}
        EXPORT_TOKEN: ${{ secrets.EXPORT_TOKEN }}
        REPORT_DATE: ${{ inputs.report_date }}
      run: |
        echo "Running monthly report script..."
        node scripts/monthly-report.js 